"""Second migration

Revision ID: ee9453df11c0
Revises: 4cbdd305035b
Create Date: 2024-05-07 12:50:41.126170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9453df11c0'
down_revision: Union[str, None] = '4cbdd305035b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=255), nullable=True))
    # op.drop_column('users', 'username')
    # Actually, I've altered  username to user_name
    op.alter_column("users", "username", new_column_name="user_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.drop_column('users', 'user_name')
    op.alter_column("users", "username", new_column_name="user_name")
    # ### end Alembic commands ###
